mixins=["hidehud.mixins.json"]
modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
[[mods]]
modId="hidehud"
version="1.0.0"
displayName="Hide HUD"
logoFile="icon.png"
authors="LAYON & NegativeStudios"
description='''Server-controlled complete HUD visibility with optional hand hiding and fade transitions.'''
[[dependencies.hidehud]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"
[[dependencies.hidehud]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"
