plugins { id 'fabric-loom' }
base { archivesName = 'hidehud-fabric-1.20.1' }
dependencies {
    minecraft 'com.mojang:minecraft:1.20.1'
    mappings loom.officialMojangMappings()
    modImplementation 'net.fabricmc:fabric-loader:0.16.5'
    modImplementation 'net.fabricmc.fabric-api:fabric-api:0.92.2+1.20.1'
}
java.toolchain.languageVersion = JavaLanguageVersion.of(17)
loom { runs { client { client() } } }
